### ISSUE TITLE
Unable to Link Teams and Github

### ISSUE THREAD

**Issue by bhattdevarsh** [integrations/microsoft-teams#149] opened 2021-08-11 06:11 UTC
I followed the README file for the process. I am trying to authenticate Teams At Github and I see Message 
```
You're almost there!

To finish linking your account with
, type

xxxxx
in the Microsoft Teams chat window.
```

when I Went back to the teams I could not find where to type this code. so I did some trial and error. but could not link these apps.

request:
- Update readme and add authentication part.
- Update message Appears on the https://teams.github.com/teams/github/oauth/. and make it more clarifying

**Comment by gauravsaralMs** [comment] 2021-08-11 06:20
closing as dupe of https://github.com/integrations/microsoft-teams/issues/141

**Closed by gauravsaralMs** 2021-08-11 06:20 UTC
Labels: bug

**Comment by sanjeev9160** [comment] 2021-08-13 11:42
@bhattdevarsh Thanks for reporting. We are unable to repro the issue but we are actively looking into it. 
Can you please add some more details like OS, is it happening in both the desktop teams app and browser(add the details of it with the version). This will help us in reproing the issue. Thanks.

**Comment by bhattdevarsh** [comment] 2021-08-13 11:52
Os : Linux
Flavor: Ubuntu 18
Using: Teams for Linux
Working for web version
Browser: Chromium
