### ISSUE TITLE
Can't remove a scheduled reminder

### ISSUE THREAD

**Issue by matt-carr** [integrations/microsoft-teams#269] opened 2022-11-30 19:26 UTC
**Describe the bug**
I am unable to delete any scheduled reminder in a public channel

**To Reproduce**
1. Create a scheduled reminder in a public channel
2. Attempt to delete the scheduled reminder
3. receive response "Please select the valid number value for minimum age."

**Expected behavior**
The reminder is deleted

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Using desktop app

**Additional context**
I am still able to edit a reminder

**Comment by NikolayTach** [comment] 2022-12-17 20:12
- [ ] Create a scheduled reminder in a public channel
- [x] Attempt to delete the scheduled reminder
- [ ] receive response "Please select the valid number value for minimum age."

**Comment by nikhilgarg1047** [comment] 2022-12-20 12:08
Hi @matt-carr / @NikolayTach - Sorry for the delayed response. Can you please share the screenshot of reminder data (like Min age) that you were are trying to delete?

**Comment by NikolayTach** [comment] 2022-12-20 18:55
```int id_sequence[3];

/* Populate the id array. */

id_sequence[0] = 30652;
id_sequence[1] = 30652;
```

**Comment by perezbr** [comment] 2022-12-21 17:31
@nikhilgarg1047 I'm having the same issue and the minimum age is set to 0, which is the default.

I changed the min age to 1 and still run into the same bug when deleting.

**Comment by nikhilgarg1047** [comment] 2022-12-27 12:13
Hi All, can you please check now and confirm if the issue is fixed?

**Comment by nikhilgarg1047** [comment] 2022-12-29 08:06
Closing this issue as the fix is released. Please reopen the issue in case you still face it.

**Closed by nikhilgarg1047** 2022-12-29 08:06 UTC
Labels: bug

**Comment by matt-carr** [comment] 2023-01-03 18:56
confirmed fixed, tyvm <3
